In [1]:
import pandas as pd

In [2]:
world = pd.read_csv('worldcities.csv')

In [4]:
Argentina = world[world['country'] == 'Argentina']

In [5]:
Argentina

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
18,Buenos Aires,Buenos Aires,-34.6033,-58.3817,Argentina,AR,ARG,"Buenos Aires, Ciudad Autónoma de",primary,16710000.0,1032717330
394,Córdoba,Cordoba,-31.4167,-64.1833,Argentina,AR,ARG,Córdoba,admin,2106734.0,1032803249
598,Rosario,Rosario,-32.9575,-60.6394,Argentina,AR,ARG,Santa Fe,minor,1276000.0,1032770677
841,Santiago del Estero,Santiago del Estero,-27.7833,-64.2667,Argentina,AR,ARG,Santiago del Estero,admin,911506.0,1032492280
1021,Comodoro Rivadavia,Comodoro Rivadavia,-45.8647,-67.4808,Argentina,AR,ARG,Chubut,minor,730266.0,1032042035
...,...,...,...,...,...,...,...,...,...,...,...
47410,Gastre,Gastre,-42.2667,-69.2167,Argentina,AR,ARG,Chubut,minor,602.0,1032815504
47427,Telsen,Telsen,-42.3833,-66.9500,Argentina,AR,ARG,Chubut,minor,544.0,1032824407
47481,Tandil,Tandil,-37.3167,-59.1333,Argentina,AR,ARG,Buenos Aires,minor,400.0,1032075057
47491,Rinconada,Rinconada,-22.4333,-66.1667,Argentina,AR,ARG,Jujuy,minor,364.0,1032429190
47585,Venado Tuerto,Venado Tuerto,-33.7500,-61.9667,Argentina,AR,ARG,Santa Fe,NaN,83.0,1032284763

In [13]:
Argentinas_cities = Argentina['admin_name'].unique()

In [14]:
Argentinas_cities

array(['Buenos Aires, Ciudad Autónoma de', 'Córdoba', 'Santa Fe',
       'Santiago del Estero', 'Chubut', 'Buenos Aires', 'Tucumán',
       'Salta', 'San Juan', 'Corrientes', 'Jujuy', 'Chaco', 'Misiones',
       'Entre Ríos', 'Formosa', 'Neuquén', 'Mendoza', 'La Rioja',
       'San Luis', 'Río Negro', 'Catamarca', 'La Pampa',
       'Tierra del Fuego, Antártida e Islas del Atlántico Sur',
       'Santa Cruz'], dtype=object)